// vue-app-spa/src/routes/Products.vue
<template>
  <div>
    <h1>Products Items: {{ hostState.storeBProducts?.products?.length || 0 }}</h1>

    <div class='grid grid-cols-4 gap-4'>
      <Card :productObj=product v-for="product in hostState.storeBProducts?.products" :key="product.id" />
    </div>

  </div>
</template>

<script setup>
import { onMounted } from 'vue';
import Card from '../components/Card.vue';
import { hostState, initHostStore, dispatchToHost } from '../store/hostStore.js';

const products = hostState?.storeBProducts?.products;

onMounted(async () => {
  await initHostStore();
  const {fetchStoreBProducts} = await import("host_app/store/apis");
  dispatchToHost(fetchStoreBProducts())
});

function addItem() {
  dispatchToHost('addToCart',{ id: Date.now(), name: 'New Product' });
}

</script>

// react-app-spa/src/routes/Products.js
import {useSelector, useDispatch} from 'react-redux'
import { useEffect } from 'react';
 const {fetchStoreAProducts} = await import("host_app/store/apis");

 import Card from '../Components/Card.js';

export default function Products() {
  const dispatch = useDispatch();
  const products = useSelector((state) => state.storeAProducts.products);

  useEffect(() => {
    dispatch(fetchStoreAProducts())
  }, [dispatch]);


  return (
    <div>
      <p>Product Listing for Store A</p>

      {products && products?.length > 0 ? (
        <div className='grid grid-cols-4 gap-4'>
          {products.map(product => ( 
            <Card key={product.id} productObj={product} />
          ))}
        </div>
      ) : (
        <p>Loading products...</p>
      )}
    </div>
  )
}
